"""Hinglish training templates (D018). Same slot convention as traindata_hi."""

VOCAB = {
    "TIME": [("kal subah", "tomorrow morning"), ("aaj shaam tak", "by this evening"),
             ("Friday tak", "by Friday"), ("Sunday ko", "on Sunday"),
             ("isi week", "this week"), ("bees tareekh tak", "by the 20th")],
    "ERRAND": [("doodh", "milk"), ("sabzi", "vegetables"), ("medicines", "medicines"),
               ("groceries", "groceries"), ("cake", "cake"), ("mithai", "sweets")],
    "PLACE": [("market", "market"), ("bakery", "bakery"), ("pharmacy", "pharmacy")],
    "APP": [("WhatsApp", "WhatsApp"), ("bank wali app", "the bank app"), ("UPI app", "the UPI app")],
    "EVENT": [("shaadi", "wedding"), ("birthday", "birthday"), ("farewell", "farewell"), ("housewarming", "housewarming")],
    "PERSON": [("Nani", "Nani"), ("Sharma uncle", "Sharma uncle"), ("Mumma", "Mumma"), ("Bua", "Bua")],
    "BILL": [("electricity bill", "electricity bill"), ("wifi bill", "wifi bill"), ("rent", "rent")],
    "TRIP": [("Gokarna", "Gokarna"), ("Manali", "Manali"), ("Udaipur", "Udaipur")],
    "ENT": [("cafe", "cafe"), ("brunch place", "brunch place"), ("momo wala", "momo place")],
    "FIX": [("geyser", "the geyser"), ("wifi router", "the wifi router"), ("balcony ka darwaza", "the balcony door")],
    "CITY": [("Pune", "Pune"), ("Bangalore", "Bangalore"), ("Canada", "Canada")],
    "DOC": [("Aadhaar card", "Aadhaar card"), ("PAN card", "PAN card"), ("license", "license")],
}

TEMPLATES = [
    dict(register="flatmates-errands", phrasing="imperative",
         senders=["Kavya", "Nikhil", "Aman"],
         slots=dict(t0="TIME", b0="BILL"),
         script="Hey sun na, {b0} {t0} pay karna hai warna late fee lagegi. Tu apna half mujhe bhej dena please. Aur receipt group pe daal dena.",
         translation="Hey listen, the {B0} has to be paid {T0} otherwise there will be a late fee. Please send me your half. And post the receipt on the group.",
         summary="{sender} says the {B0} is due {T0} and asks for the listener's half plus the receipt on the group.",
         items=[("Send {sender} your half of the {B0}", "t0", "confirmed"),
                ("Post the receipt on the group", None, "confirmed")]),
    dict(register="friends-errands", phrasing="imperative",
         senders=["Rohan", "Sneha", "Varun"],
         slots=dict(t0="TIME", i0="ERRAND", p0="PLACE", e0="EVENT"),
         script="Bro, {e0} wale function ke liye {i0} ka order de dena us {p0} se, {t0} pickup bolna. Budget ki tension mat le, settle kar lenge.",
         translation="Bro, place the order for {I0} for the {E0} function at that {P0}, tell them {T0} pickup. Don't worry about the budget, we will settle it.",
         summary="{sender} asks to order {I0} from the {P0} for the {E0} function, with pickup {T0}.",
         items=[("Order {I0} from the {P0} for the {E0} function", "t0", "confirmed")]),
    dict(register="family-errands", phrasing="question",
         senders=["Didi", "Bhai", "Mumma"],
         slots=dict(t0="TIME", app0="APP"),
         script="Sun, ek chhota sa favour chahiye. Kya tu {t0} Mumma ke phone me {app0} set kar dega? Wo roz mujhse poochti hain aur mujhe time nahi mil raha. Ho jayega na?",
         translation="Listen, I need a small favour. Will you set up {APP0} on Mumma's phone {T0}? She asks me every day and I am not getting the time. It will get done, right?",
         summary="{sender} asks — as a question — to set up {APP0} on Mumma's phone {T0}.",
         items=[("Set up {APP0} on Mumma's phone", "t0", "confirmed")]),
    dict(register="friends-errands", phrasing="colloquial",
         senders=["Aman", "Kavya", "Dev"],
         slots=dict(t0="TIME", d0="DOC"),
         script="Yaar ek kaam kar dena please, apna {d0} renew karwa le {t0}, baad me bahut jhanjhat hota hai. Abhi online ho jata hai easily, das minute ka kaam hai.",
         translation="Yaar, please do one thing, get your {D0} renewed {T0}, later it becomes a big hassle. It happens online easily now, it is ten minutes of work.",
         summary="{sender} asks to get the {D0} renewed {T0} since it is quick online now.",
         items=[("Renew the {D0}", "t0", "confirmed")]),
    dict(register="flatmates-errands", phrasing="implicit",
         senders=["Kavya", "Nikhil"],
         slots=dict(t0="TIME", f0="FIX"),
         script="Uff yaar, main abhi nikal gayi hoon aur lagta hai {f0} on hi reh gaya hai. Baarish bhi start ho gayi hai aur main {t0} se pehle wapas nahi aa paungi kisi haal me.",
         translation="Ugh yaar, I have just left and I think {F0} has been left on. It has also started raining and there is no way I can come back before {T0}.",
         summary="{sender} has left with {F0} left on and cannot return before {T0} — implying the listener should deal with it.",
         items=[("Check and turn off {F0}", None, "confirmed")]),
    dict(register="friends-trip-planning", phrasing="colloquial",
         senders=["Rohan", "Priya", "Varun"],
         slots=dict(tr0="TRIP"),
         script="Yaar soch raha tha next long weekend pe {tr0} chalein, sasta bhi padega us time. Abhi kuch book mat karna, pehle sab se pooch lete hain. Bas idea hai abhi.",
         translation="Yaar, I was thinking we could go to {TR0} on the next long weekend, it will be cheaper at that time too. Don't book anything yet, let's ask everyone first. It is just an idea for now.",
         summary="{sender} floats a {TR0} trip for the next long weekend; nothing to book until the group is asked.",
         items=[("Consider a trip to {TR0}", "next long weekend", "tentative")]),
    dict(register="friends-planning", phrasing="question",
         senders=["Priya", "Sneha", "Ishita"],
         slots=dict(t0="TIME", en0="ENT"),
         script="Office ke paas wala naya {en0} dekha hai? {t0} try karein kya? Abhi confirm mat kar, mood dekh ke decide karenge. Waise reviews acche hain uske.",
         translation="Have you seen the new {EN0} near office? Shall we try it {T0}? Don't confirm yet, we will decide based on the mood. Its reviews are good, by the way.",
         summary="{sender} tentatively suggests trying the new {EN0} {T0}, to be decided later.",
         items=[("Consider trying the new {EN0}", "t0", "tentative")]),
    dict(register="family-event-planning", phrasing="imperative",
         senders=["Cousin Tanvi", "Didi", "Bhai"],
         slots=dict(t0="TIME", per0="PERSON", e0="EVENT"),
         script="{per0} ke {e0} wale video ke liye sab log clips bhej rahe hain. Tu apni 30 second wali clip {t0} bhej de mujhe, main edit karungi. Aur soch rahe the ki ek group gift bhi karein, dekhte hain.",
         translation="Everyone is sending clips for {PER0}'s {E0} video. You send me your 30 second clip {T0}, I will edit it. And we were thinking of also doing a group gift, we will see.",
         summary="{sender} asks for a 30-second clip for {PER0}'s {E0} video {T0}, and tentatively mentions a group gift.",
         items=[("Send {sender} a 30-second clip for {PER0}'s {E0} video", "t0", "confirmed"),
                ("Consider a group gift", None, "tentative")]),
    dict(register="flatmates-errands", phrasing="imperative",
         senders=["Nikhil", "Aman"],
         slots=dict(t0="TIME", i0="ERRAND", p0="PLACE", b0="BILL"),
         script="Oye, {b0} main aaj pay kar raha hoon, tu tension mat le uski. Bas tu {t0} {p0} se {i0} le aana, main us side nahi jaunga aaj.",
         translation="Hey, I am paying the {B0} today, you don't worry about it. You just bring {I0} from the {P0} {T0}, I will not go that side today.",
         summary="{sender} is paying the {B0} themselves and asks only that the listener bring {I0} from the {P0} {T0}.",
         items=[("Bring {I0} from the {P0}", "t0", "confirmed")]),
    dict(register="flatmates-chat", phrasing=None,
         senders=["Nikhil", "Kavya"],
         slots=dict(b0="BILL", f0="FIX"),
         script="Oye update: {b0} maine pay kar diya hai, split baad me kar lenge aaram se. Aur {f0} bhi theek ho gaya, banda aaya tha aaj. Bas batana tha. Party banti hai meri waise.",
         translation="Hey, update: I have paid the {B0}, we will do the split later at leisure. And {F0} is also fixed, the guy came today. Just wanted to tell you. I do deserve a party for this, by the way.",
         summary="{sender} reports the {B0} is paid and {F0} is fixed — just an update, nothing to do.",
         items=[]),
    dict(register="friends-chat", phrasing=None,
         senders=["Cousin Aditi", "Meera", "Dev"],
         slots=dict(per0="PERSON", c0="CITY"),
         script="Arre suna tune? {per0} ke bete ne {c0} me flat book kar liya, LOL itni jaldi. Aunty ne pure mohalle me mithai baanti. Sab log yahi discuss kar rahe hain. Chal, baad me baat karte hain.",
         translation="Hey, did you hear? {PER0}'s son has booked a flat in {C0}, LOL so quickly. Aunty distributed sweets in the whole neighbourhood. Everyone is discussing just this. Okay, we will talk later.",
         summary="{sender} shares gossip that {PER0}'s son booked a flat in {C0} and sweets were distributed. Pure chat, no tasks.",
         items=[]),
    dict(register="friends-chat", phrasing=None,
         senders=["Ishita", "Dev", "Priya"],
         slots=dict(en0="ENT"),
         script="Hey, bas batana tha ki main ab theek hoon, fever utar gaya kal raat se. Doctor ne bola viral hi tha. Us din wale {en0} ka plan cancel karna pada tha, sad. Tu apna khayal rakh, season kharab hai.",
         translation="Hey, just wanted to tell you that I am fine now, the fever came down last night. The doctor said it was just viral. Had to cancel that day's {EN0} plan, sad. You take care of yourself, the season is bad.",
         summary="{sender} shares a recovery update after a viral fever and general take-care wishes. No tasks.",
         items=[]),
]
