"""Bengali training templates (D018). Same slot convention as traindata_hi."""

VOCAB = {
    "TIME": [("কাল সকালে", "tomorrow morning"), ("আজ বিকেলের মধ্যে", "by this afternoon"),
             ("শনিবারের মধ্যে", "by Saturday"), ("রবিবার", "on Sunday"),
             ("এই সপ্তাহে", "this week"), ("কুড়ি তারিখের মধ্যে", "by the 20th")],
    "ERRAND": [("দুধ", "milk"), ("ডিম", "eggs"), ("ওষুধ", "medicine"),
               ("মিষ্টি", "sweets"), ("সবজি", "vegetables"), ("ফল", "fruit")],
    "PLACE": [("বাজার", "market"), ("দোকান", "shop"), ("ওষুধের দোকান", "pharmacy")],
    "APPT": [("ডাক্তার", "doctor"), ("চোখের ডাক্তার", "eye doctor"), ("দাঁতের ডাক্তার", "dentist")],
    "APP": [("হোয়াটসঅ্যাপ", "WhatsApp"), ("ব্যাঙ্কের অ্যাপ", "the bank app"), ("ট্রেনের অ্যাপ", "the train app")],
    "EVENT": [("বিয়ে", "wedding"), ("জন্মদিন", "birthday"), ("গৃহপ্রবেশ", "housewarming"), ("পুজো", "Pujo")],
    "PERSON": [("মামা", "Mama"), ("পিসি", "Pishi"), ("দিদা", "Dida"), ("কাকু", "Kaku")],
    "BILL": [("কারেন্টের বিল", "electricity bill"), ("জলের বিল", "water bill"), ("ফোনের রিচার্জ", "phone recharge")],
    "TRIP": [("দার্জিলিং", "Darjeeling"), ("শান্তিনিকেতন", "Santiniketan"), ("দিঘা", "Digha")],
    "FEST": [("পুজোয়", "Pujo"), ("গরমের ছুটিতে", "the summer holidays"), ("শীতে", "the winter")],
    "ENT": [("ক্যাফে", "cafe"), ("রেস্টুরেন্ট", "restaurant"), ("রোলের দোকান", "roll shop")],
    "FIX": [("কল", "the tap"), ("গিজার", "the geyser"), ("পাখা", "the fan")],
    "CITY": [("ব্যাঙ্গালোর", "Bangalore"), ("পুনে", "Pune"), ("হায়দরাবাদ", "Hyderabad")],
}

TEMPLATES = [
    dict(register="family-errands", phrasing="imperative",
         senders=["Ma", "Baba", "Didi"],
         slots=dict(t0="TIME", i0="ERRAND", p0="PLACE", b0="BILL"),
         script="শোন বাবু, {t0} {p0} থেকে {i0} নিয়ে আসিস, ঘরে একদম নেই। আর {b0}টাও দিয়ে দিস, লাস্ট ডেট পেরিয়ে যাবে।",
         translation="Listen babu, bring {I0} from the {P0} {T0}, there is none at all at home. And also pay the {B0}, the last date will pass.",
         summary="{sender} asks to bring {I0} from the {P0} {T0} and to pay the {B0} before the last date.",
         items=[("Bring {I0} from the {P0}", "t0", "confirmed"),
                ("Pay the {B0}", None, "confirmed")]),
    dict(register="family-errands", phrasing="imperative",
         senders=["Ma", "Dada"],
         slots=dict(t0="TIME", a0="APPT", per0="PERSON"),
         script="বাবু, {per0}-র শরীরটা ভালো যাচ্ছে না। তুই {t0} অ্যাপ থেকে {a0}-র একটা অ্যাপয়েন্টমেন্ট বুক করে দিস তো। আমরা দুজনেই যাব।",
         translation="Babu, {PER0}'s health has not been good. You book a {A0} appointment from the app {T0}. Both of us will go.",
         summary="{sender} says {PER0} is unwell and asks to book a {A0} appointment via the app {T0}.",
         items=[("Book a {A0} appointment for {PER0} via the app", "t0", "confirmed")]),
    dict(register="family-errands", phrasing="question",
         senders=["Baba", "Dida", "Pishi"],
         slots=dict(t0="TIME", app0="APP"),
         script="বাবু, একটা কথা ছিল। তুই কি {t0} আমার ফোনে {app0}টা করে দিতে পারবি? আমার মাথায় ঢোকে না এসব। পারবি তো?",
         translation="Babu, there was one thing. Will you be able to set up {APP0} on my phone {T0}? These things do not get into my head. You can, right?",
         summary="{sender} asks — as a question — to set up {APP0} on their phone {T0}.",
         items=[("Set up {APP0} on {sender}'s phone", "t0", "confirmed")]),
    dict(register="family-event-planning", phrasing="colloquial",
         senders=["Didi", "Boudi", "Dada"],
         slots=dict(t0="TIME", i0="ERRAND", e0="EVENT"),
         script="এই শোন না, {e0}-র ফাংশনের জন্য {i0}টা তুই-ই নিয়ে আসিস প্লিজ, আমার সময় হবে না। {t0} হয়ে গেলে খুব ভালো হয়।",
         translation="Hey listen, please bring the {I0} for the {E0} function yourself, I will not have the time. It would be very good if it happens {T0}.",
         summary="{sender} asks to buy the {I0} for the {E0} function, ideally {T0}.",
         items=[("Buy {I0} for the {E0} function", "t0", "confirmed")]),
    dict(register="family-errands", phrasing="implicit",
         senders=["Ma", "Baba"],
         slots=dict(t0="TIME", vis0="PERSON"),
         script="বাবু, {t0} {vis0} বাড়ি দেখতে আসছেন, আর আমি সেদিন সারাদিন বাইরে থাকব। বাড়িতে দরজা খোলার কেউ নেই। বুঝতে পারছিস তো আমি কী বলছি?",
         translation="Babu, {VIS0} is coming to see the house {T0}, and I will be out the whole of that day. There is no one at home to open the door. You understand what I am saying, right?",
         summary="{VIS0} is visiting {T0} while {sender} is out all day and no one is home — implying the listener must be there.",
         items=[("Be at home to receive {VIS0}", "t0", "confirmed")]),
    dict(register="family-planning", phrasing="colloquial",
         senders=["Dada", "Didi", "Kaku"],
         slots=dict(f0="FEST", tr0="TRIP"),
         script="ভাবছিলাম এবার {f0} সবাই মিলে {tr0} গেলে কেমন হয়। এখনো কিছুই ঠিক নেই, জাস্ট মাথায় এল। সবার মত দেখে ঠিক করা যাবে, তাড়া নেই।",
         translation="I was thinking how it would be if all of us went to {TR0} together for {F0} this time. Nothing is fixed at all yet, it just came to my mind. We can decide after seeing everyone's opinion, no hurry.",
         summary="{sender} floats the idea of a family trip to {TR0} for {F0}; nothing is fixed yet.",
         items=[("Consider a family trip to {TR0}", "f0", "tentative")]),
    dict(register="friends-planning", phrasing="question",
         senders=["Riya", "Sourav", "Arka"],
         slots=dict(t0="TIME", en0="ENT"),
         script="এই, {t0} ওই নতুন {en0}টা ট্রাই করলে কেমন হয়? এখনই কনফার্ম করিস না, বাকিদেরও জিজ্ঞেস করে নিই। ভেবে বলিস।",
         translation="Hey, how would it be if we tried that new {EN0} {T0}? Do not confirm right away, let me ask the others too. Think and tell me.",
         summary="{sender} tentatively suggests trying the new {EN0} {T0}, pending the others.",
         items=[("Consider trying the new {EN0}", "t0", "tentative")]),
    dict(register="family-event-planning", phrasing="imperative",
         senders=["Baba", "Boudi"],
         slots=dict(t0="TIME", e0="EVENT"),
         script="{e0}-র কাজ শুরু হয়ে গেছে। তুই {t0} গেস্ট লিস্টটা ফাইনাল করে পাঠিয়ে দিস, পাকা কথা। আর ভাবছিলাম ডেকরেটরের সঙ্গেও একবার কথা বলি, সেটা দেখা যাবে।",
         translation="The {E0} work has started. You finalize and send the guest list {T0}, that is final. And I was thinking of also talking to the decorator once, we will see about that.",
         summary="{sender} asks for the final guest list for the {E0} {T0}, and tentatively mentions the decorator.",
         items=[("Send the final guest list for the {E0}", "t0", "confirmed"),
                ("Talk to the decorator", None, "tentative")]),
    dict(register="family-errands", phrasing="imperative",
         senders=["Baba", "Dada"],
         slots=dict(t0="TIME", i0="ERRAND", p0="PLACE", b0="BILL"),
         script="শোন, {b0}টা আমি আজই দিয়ে দিচ্ছি, তোকে ওটা নিয়ে ভাবতে হবে না। তুই শুধু {t0} {p0} থেকে {i0} নিয়ে আসিস, আমি ওদিকে যেতে পারব না।",
         translation="Listen, I am paying the {B0} today itself, you do not have to think about that. You only bring {I0} from the {P0} {T0}, I will not be able to go that side.",
         summary="{sender} is handling the {B0} themselves and asks only that the listener bring {I0} from the {P0} {T0}.",
         items=[("Bring {I0} from the {P0}", "t0", "confirmed")]),
    dict(register="family-chat", phrasing=None,
         senders=["Baba", "Ma"],
         slots=dict(b0="BILL", f0="FIX"),
         script="হ্যাঁ শোন, {b0}টা আমি দিয়ে দিয়েছি, তোকে আর কিছু করতে হবে না। আর {f0}টাও সারানো হয়ে গেছে, মিস্ত্রি এসেছিল আজ। ব্যস, এইটুকুই বলার ছিল। ভালো থাকিস।",
         translation="Yes listen, I have paid the {B0}, you do not have to do anything more. And {F0} has also been repaired, the repairman came today. That is all I had to say. Stay well.",
         summary="{sender} reports the {B0} is already paid and {F0} has been repaired — just an update, nothing to do.",
         items=[]),
    dict(register="family-chat", phrasing=None,
         senders=["Ma", "Pishi", "Didi"],
         slots=dict(per0="PERSON", c0="CITY"),
         script="এই জানিস? {per0}-র ছেলে {c0}-তে চাকরি পেয়েছে। ওরা পাড়ায় সবাইকে মিষ্টি খাইয়েছে, সবাই এই নিয়েই কথা বলছে। যাক গে, পরে কথা হবে।",
         translation="Hey, you know? {PER0}'s son has got a job in {C0}. They fed sweets to everyone in the neighbourhood, everyone is talking only about this. Anyway, we will talk later.",
         summary="{sender} shares news that {PER0}'s son got a job in {C0} and sweets were distributed. Pure chat, no tasks.",
         items=[]),
    dict(register="family-chat", phrasing=None,
         senders=["Dida", "Ma", "Pishi"],
         slots=dict(per0="PERSON"),
         script="দাদুভাই, কেমন আছিস? ঠিক করে খাওয়া-দাওয়া করিস, রাত জেগে কাজ করিস না। এখানে সবাই ভালো আছি, {per0} তোর কথা জিজ্ঞেস করছিল। শরীরের যত্ন নিস।",
         translation="Dadubhai, how are you? Eat your meals properly, do not stay up at night working. All of us here are well, {PER0} was asking about you. Take care of your health.",
         summary="{sender} checks in with general care advice — eat properly, don't stay up working — and says {PER0} asked after the listener. No tasks.",
         items=[]),
]
