"""Tamil training templates (D018). Same slot convention as traindata_hi."""

VOCAB = {
    "TIME": [("நாளைக்கு காலையில", "tomorrow morning"), ("இன்னைக்கு சாயங்காலத்துக்குள்ள", "by this evening"),
             ("வெள்ளிக்கிழமைக்குள்ள", "by Friday"), ("ஞாயிற்றுக்கிழமை", "on Sunday"),
             ("இந்த வாரம்", "this week"), ("இருபதாம் தேதிக்குள்ள", "by the 20th")],
    "ERRAND": [("பால்", "milk"), ("மருந்து", "medicine"), ("காய்கறி", "vegetables"),
               ("பழம்", "fruit"), ("சாமான்", "groceries"), ("ஸ்வீட்", "sweets")],
    "PLACE": [("கடை", "shop"), ("மார்க்கெட்", "market"), ("பார்மசி", "pharmacy")],
    "APPT": [("டாக்டர்", "doctor"), ("கண் டாக்டர்", "eye doctor"), ("பல் டாக்டர்", "dentist")],
    "APP": [("வாட்ஸ்அப்", "WhatsApp"), ("பேங்க் ஆப்", "the bank app"), ("ரெயில் ஆப்", "the train app")],
    "EVENT": [("கல்யாணம்", "wedding"), ("பர்த்டே", "birthday"), ("கிரஹப்பிரவேசம்", "housewarming")],
    "PERSON": [("மாமா", "Mama"), ("சித்தி", "Chithi"), ("பாட்டி", "Paatti"), ("அத்தை", "Athai")],
    "BILL": [("கரண்ட் பில்", "electricity bill"), ("தண்ணி பில்", "water bill"), ("போன் ரீசார்ஜ்", "phone recharge")],
    "TRIP": [("மகாபலிபுரம்", "Mahabalipuram"), ("கொடைக்கானல்", "Kodaikanal"), ("பாண்டிச்சேரி", "Pondicherry")],
    "FEST": [("தீபாவளிக்கு", "Diwali"), ("பொங்கலுக்கு", "Pongal"), ("லீவுக்கு", "the holidays")],
    "ENT": [("கஃபே", "cafe"), ("ஹோட்டல்", "restaurant"), ("சாட் கடை", "chaat stall")],
    "FIX": [("குழாய்", "the tap"), ("கீசர்", "the geyser"), ("பேன்", "the fan")],
    "CITY": [("சென்னை", "Chennai"), ("பெங்களூரு", "Bangalore"), ("கோவை", "Coimbatore")],
}

TEMPLATES = [
    dict(register="family-errands", phrasing="imperative",
         senders=["Amma", "Appa", "Akka"],
         slots=dict(t0="TIME", i0="ERRAND", p0="PLACE", b0="BILL"),
         script="டேய் கேளு, {t0} {p0}ல {i0} வாங்கிட்டு வா, வீட்ல கொஞ்சம் கூட இல்ல. அப்புறம் {b0} கட்டிடு, லாஸ்ட் டேட் போயிடும்.",
         translation="Hey listen, buy {I0} at the {P0} {T0} and bring it, there is none at all at home. Then pay the {B0}, the last date will pass.",
         summary="{sender} asks to bring {I0} from the {P0} {T0} and to pay the {B0} before the last date.",
         items=[("Bring {I0} from the {P0}", "t0", "confirmed"),
                ("Pay the {B0}", None, "confirmed")]),
    dict(register="family-errands", phrasing="imperative",
         senders=["Amma", "Anna"],
         slots=dict(t0="TIME", a0="APPT", per0="PERSON"),
         script="கண்ணா, {per0}க்கு உடம்பு சரியில்ல. நீ {t0} ஆப்ல {a0} அப்பாயின்ட்மென்ட் புக் பண்ணிடு. நாங்க ரெண்டு பேரும் போயிட்டு வர்றோம்.",
         translation="Kanna, {PER0} is not well. You book a {A0} appointment on the app {T0}. The two of us will go and come.",
         summary="{sender} says {PER0} is unwell and asks to book a {A0} appointment via the app {T0}.",
         items=[("Book a {A0} appointment for {PER0} via the app", "t0", "confirmed")]),
    dict(register="family-errands", phrasing="question",
         senders=["Akka", "Appa", "Chithi"],
         slots=dict(t0="TIME", app0="APP"),
         script="தம்பி, ஒரு உதவி. {t0} அம்மாவோட போன்ல {app0} போட்டுத் தர முடியுமா உன்னால? அவங்க தினமும் கேக்குறாங்க, எனக்கு நேரம் கிடைக்கல. முடியும்ல?",
         translation="Thambi, one favour. Would you be able to set up {APP0} on Amma's phone {T0}? She asks every day, and I am not getting the time. You can, right?",
         summary="{sender} asks — as a question — to set up {APP0} on Amma's phone {T0}.",
         items=[("Set up {APP0} on Amma's phone", "t0", "confirmed")]),
    dict(register="family-event-planning", phrasing="colloquial",
         senders=["Akka", "Anna", "Chithi"],
         slots=dict(t0="TIME", i0="ERRAND", e0="EVENT"),
         script="ஏய் கேளு, {e0} பங்க்ஷனுக்கு {i0} நீயே வாங்கிடு ப்ளீஸ், எனக்கு டைம் கிடைக்காது. {t0} வாங்கிட்டா நல்லா இருக்கும்.",
         translation="Hey listen, please buy the {I0} for the {E0} function yourself, I will not get the time. It would be good if you buy it {T0}.",
         summary="{sender} asks to buy the {I0} for the {E0} function, ideally {T0}.",
         items=[("Buy {I0} for the {E0} function", "t0", "confirmed")]),
    dict(register="family-errands", phrasing="implicit",
         senders=["Amma", "Appa"],
         slots=dict(t0="TIME", vis0="PERSON"),
         script="கண்ணா, {t0} {vis0} வீட்டுக்கு வர்றாங்க, நான் அன்னைக்கு முழுக்க வெளியில இருப்பேன். வீட்ல கதவு திறக்க யாரும் இல்ல. புரியுதுல்ல நான் என்ன சொல்றேன்னு?",
         translation="Kanna, {VIS0} is coming home {T0}, and I will be out the whole of that day. There is no one at home to open the door. You understand what I am saying, right?",
         summary="{VIS0} is visiting {T0} while {sender} is out all day and no one is home — implying the listener must be there.",
         items=[("Be at home to receive {VIS0}", "t0", "confirmed")]),
    dict(register="family-planning", phrasing="colloquial",
         senders=["Anna", "Akka", "Appa"],
         slots=dict(f0="FEST", tr0="TRIP"),
         script="{f0} இந்த தடவை எல்லாரும் சேர்ந்து {tr0} போலாமான்னு யோசிச்சுட்டு இருந்தேன். இன்னும் எதுவும் முடிவு பண்ணல, சும்மா ஒரு ஐடியாதான். எல்லார் மூடும் பாத்து முடிவு பண்ணலாம்.",
         translation="I was thinking whether all of us together could go to {TR0} for {F0} this time. Nothing is decided yet, it is just an idea. We can decide after seeing everyone's mood.",
         summary="{sender} floats the idea of a family trip to {TR0} for {F0}; nothing is decided yet.",
         items=[("Consider a family trip to {TR0}", "f0", "tentative")]),
    dict(register="friends-planning", phrasing="question",
         senders=["Divya", "Karthik", "Suresh"],
         slots=dict(t0="TIME", en0="ENT"),
         script="மச்சி, {t0} அந்த புது {en0} ட்ரை பண்ணலாமா? இப்பவே கன்ஃபார்ம் பண்ண வேண்டாம், மத்தவங்க கிட்டயும் கேட்டுடலாம். யோசிச்சு சொல்லு.",
         translation="Machi, shall we try that new {EN0} {T0}? No need to confirm right away, we can ask the others too. Think and tell me.",
         summary="{sender} tentatively suggests trying the new {EN0} {T0}, pending the others.",
         items=[("Consider trying the new {EN0}", "t0", "tentative")]),
    dict(register="family-event-planning", phrasing="imperative",
         senders=["Appa", "Anna"],
         slots=dict(t0="TIME", e0="EVENT"),
         script="{e0} வேலைகள் ஆரம்பிச்சாச்சு. நீ {t0} கெஸ்ட் லிஸ்ட் ஃபைனல் பண்ணி அனுப்பிடு, கண்டிப்பா. அப்புறம் டெகரேஷன்காரன் கிட்ட பேசலாமான்னு பாக்குறோம், அத நிதானமா பார்க்கலாம்.",
         translation="The {E0} work has started. You finalize and send the guest list {T0}, definitely. Then we are seeing whether to talk to the decorator, we can look at that calmly.",
         summary="{sender} asks for the final guest list for the {E0} {T0}, and tentatively mentions the decorator.",
         items=[("Send the final guest list for the {E0}", "t0", "confirmed"),
                ("Talk to the decorator", None, "tentative")]),
    dict(register="family-errands", phrasing="imperative",
         senders=["Appa", "Anna"],
         slots=dict(t0="TIME", i0="ERRAND", p0="PLACE", b0="BILL"),
         script="கேளு, {b0} நான் இன்னைக்கே கட்டிடறேன், அத நீ கவலைப்படாதே. நீ மட்டும் {t0} {p0}ல {i0} வாங்கிட்டு வா, என்னால அந்த பக்கம் வர முடியாது.",
         translation="Listen, I will pay the {B0} today itself, don't you worry about that. You only bring {I0} from the {P0} {T0}, I cannot come to that side.",
         summary="{sender} is handling the {B0} themselves and asks only that the listener bring {I0} from the {P0} {T0}.",
         items=[("Bring {I0} from the {P0}", "t0", "confirmed")]),
    dict(register="family-chat", phrasing=None,
         senders=["Appa", "Amma"],
         slots=dict(b0="BILL", f0="FIX"),
         script="கண்ணா, {b0} நான் கட்டிட்டேன், நீ எதுவும் பண்ண வேண்டாம். {f0}யும் சரி பண்ணியாச்சு, ஆளு வந்திருந்தான் இன்னைக்கு. இத சொல்லத்தான் கூப்பிட்டேன். உடம்ப பாத்துக்கோ.",
         translation="Kanna, I have paid the {B0}, you do not have to do anything. {F0} has also been fixed, the man came today. I called just to say this. Take care of your health.",
         summary="{sender} reports the {B0} is already paid and {F0} has been fixed — just an update, nothing to do.",
         items=[]),
    dict(register="family-chat", phrasing=None,
         senders=["Amma", "Chithi", "Akka"],
         slots=dict(per0="PERSON", c0="CITY"),
         script="டேய் கேட்டியா? {per0} பையனுக்கு {c0}ல வேலை கிடைச்சிருச்சாம். வீட்ல எல்லாருக்கும் ஸ்வீட் வாங்கி வந்து குடுத்தாங்க. ஊரே இத பத்திதான் பேசுது. சரி, அப்புறம் பேசலாம்.",
         translation="Hey, did you hear? {PER0}'s son has apparently got a job in {C0}. They bought and gave sweets to everyone at home. The whole town is talking only about this. Okay, we will talk later.",
         summary="{sender} shares news that {PER0}'s son got a job in {C0} and sweets were distributed. Pure chat, no tasks.",
         items=[]),
    dict(register="family-chat", phrasing=None,
         senders=["Paatti", "Chithi", "Amma"],
         slots=dict(per0="PERSON"),
         script="கண்ணா எப்படி இருக்க? சாப்பாடு ஒழுங்கா சாப்டு, ராத்திரி முழுக்க வேலை பாக்காதே. இங்க எல்லாரும் நல்லா இருக்கோம், {per0} உன்ன கேட்டாங்க. உடம்ப கவனிச்சுக்கோ.",
         translation="Kanna, how are you? Eat your food properly, do not work all night. All of us here are fine, {PER0} asked after you. Take care of your health.",
         summary="{sender} checks in with general care advice — eat properly, don't overwork — and says {PER0} asked after the listener. No tasks.",
         items=[]),
]
