"""Hindi training templates (D018). Slot convention: {x0} native in script,
{X0} English in translation/summary/tasks; due values name a slot key or None."""

VOCAB = {
    "TIME": [("कल सुबह", "tomorrow morning"), ("आज शाम तक", "by this evening"),
             ("शुक्रवार तक", "by Friday"), ("रविवार को", "on Sunday"),
             ("इसी हफ़्ते", "this week"), ("बीस तारीख़ तक", "by the 20th")],
    "ERRAND": [("दूध", "milk"), ("सब्ज़ी", "vegetables"), ("दवा", "medicine"),
               ("राशन", "groceries"), ("फल", "fruit"), ("मिठाई", "sweets")],
    "PLACE": [("बाज़ार", "market"), ("मंडी", "vegetable market"), ("दुकान", "shop")],
    "APPT": [("डॉक्टर", "doctor"), ("डेंटिस्ट", "dentist"), ("आँखों के डॉक्टर", "eye doctor")],
    "APP": [("व्हाट्सऐप", "WhatsApp"), ("बैंक वाली ऐप", "the bank app"), ("ट्रेन वाली ऐप", "the train app")],
    "EVENT": [("शादी", "wedding"), ("बर्थडे", "birthday"), ("सगाई", "engagement"), ("गृहप्रवेश", "housewarming")],
    "PERSON": [("बुआ", "Bua"), ("मामा जी", "Mama ji"), ("दादी", "Dadi"), ("चाचा जी", "Chacha ji")],
    "BILL": [("बिजली का बिल", "electricity bill"), ("पानी का बिल", "water bill"), ("फोन का रिचार्ज", "phone recharge")],
    "TRIP": [("नैनीताल", "Nainital"), ("जयपुर", "Jaipur"), ("ऋषिकेश", "Rishikesh")],
    "FEST": [("दिवाली", "Diwali"), ("होली", "Holi"), ("छुट्टियों", "the holidays")],
    "ENT": [("कैफ़े", "cafe"), ("रेस्टोरेंट", "restaurant"), ("ढाबा", "dhaba")],
    "FIX": [("नल", "the tap"), ("गीज़र", "the geyser"), ("पंखा", "the fan")],
    "CITY": [("पुणे", "Pune"), ("बैंगलोर", "Bangalore"), ("इंदौर", "Indore")],
}

TEMPLATES = [
    dict(register="family-errands", phrasing="imperative",
         senders=["Mummy", "Papa", "Didi"],
         slots=dict(t0="TIME", i0="ERRAND", p0="PLACE", b0="BILL"),
         script="सुन बेटा, {t0} {p0} से {i0} लेते आना, घर में बिलकुल नहीं है। और {b0} भी भर दियो, आख़िरी तारीख़ निकल जाएगी।",
         translation="Listen beta, bring {I0} from the {P0} {T0}, there is none at all at home. And also pay the {B0}, the last date will pass.",
         summary="{sender} asks to bring {I0} from the {P0} {T0} and to pay the {B0} before the last date.",
         items=[("Bring {I0} from the {P0}", "t0", "confirmed"),
                ("Pay the {B0}", None, "confirmed")]),
    dict(register="family-errands", phrasing="imperative",
         senders=["Mummy", "Papa"],
         slots=dict(t0="TIME", a0="APPT", per0="PERSON"),
         script="बेटा, {per0} की तबीयत ठीक नहीं चल रही। तू ऐसा कर, {t0} {a0} की अपॉइंटमेंट बुक कर दे ऐप से। हम दोनों चले जाएँगे।",
         translation="Beta, {PER0}'s health has not been good. Do one thing — book a {A0} appointment from the app {T0}. The two of us will go.",
         summary="{sender} says {PER0} is unwell and asks to book a {A0} appointment via the app {T0}.",
         items=[("Book a {A0} appointment for {PER0} via the app", "t0", "confirmed")]),
    dict(register="family-errands", phrasing="question",
         senders=["Papa", "Dadi", "Mummy"],
         slots=dict(t0="TIME", app0="APP"),
         script="बेटा, एक काम था। क्या तू {t0} मेरे फोन में {app0} डाल देगा? मुझसे होता नहीं है ये सब। हो जाएगा ना?",
         translation="Beta, there was one thing. Will you set up {APP0} on my phone {T0}? I can't manage these things. It will get done, right?",
         summary="{sender} asks — phrased as a question — to set up {APP0} on their phone {T0}.",
         items=[("Set up {APP0} on {sender}'s phone", "t0", "confirmed")]),
    dict(register="family-event-planning", phrasing="colloquial",
         senders=["Didi", "Bhaiya", "Cousin Tanvi"],
         slots=dict(t0="TIME", i0="ERRAND", e0="EVENT"),
         script="अरे सुन ना, {e0} वाले फंक्शन के लिए {i0} तू ही ले लियो प्लीज़, मुझसे टाइम नहीं निकलेगा। {t0} हो जाए तो बढ़िया।",
         translation="Hey listen, please get the {I0} for the {E0} function yourself, I won't be able to find the time. If it happens {T0}, great.",
         summary="{sender} asks to buy the {I0} for the {E0} function, ideally {T0}.",
         items=[("Buy {I0} for the {E0} function", "t0", "confirmed")]),
    dict(register="family-errands", phrasing="implicit",
         senders=["Mummy", "Papa"],
         slots=dict(t0="TIME", vis0="PERSON"),
         script="बेटा, {t0} {vis0} घर देखने आ रहे हैं और मैं उस दिन सारा दिन बाहर रहूँगी। घर पे दरवाज़ा खोलने वाला कोई नहीं है। समझ रहा है ना मैं क्या कह रही हूँ?",
         translation="Beta, {VIS0} is coming to see the house {T0} and I will be out the whole day. There is no one at home to open the door. You understand what I am saying, right?",
         summary="{VIS0} is visiting {T0} while {sender} is out all day and no one is home — implying the listener must be there.",
         items=[("Be at home to receive {VIS0}", "t0", "confirmed")]),
    dict(register="family-planning", phrasing="colloquial",
         senders=["Bhaiya", "Didi", "Chacha ji"],
         slots=dict(f0="FEST", tr0="TRIP"),
         script="सोच रहा था इस बार {f0} पे सब लोग {tr0} चलें। अभी कुछ पक्का नहीं है, बस आइडिया है। सबका मूड देख लेंगे, आराम से।",
         translation="I was thinking that this time for {F0} all of us could go to {TR0}. Nothing is fixed yet, it is just an idea. We will see everyone's mood, no rush.",
         summary="{sender} floats the idea of a family trip to {TR0} for {F0}; nothing is fixed yet.",
         items=[("Consider a family trip to {TR0}", "f0", "tentative")]),
    dict(register="friends-planning", phrasing="question",
         senders=["Priya", "Rohan", "Meera"],
         slots=dict(t0="TIME", en0="ENT"),
         script="यार, {t0} वो नया {en0} ट्राई करें क्या? अभी पक्का मत करते हैं, पहले बाक़ी लोगों से भी पूछ लेते हैं। सोच के बता।",
         translation="Yaar, shall we try that new {EN0} {T0}? Let's not make it final yet, let's first ask the others too. Think and tell me.",
         summary="{sender} tentatively suggests trying the new {EN0} {T0}, pending checking with the others.",
         items=[("Consider trying the new {EN0}", "t0", "tentative")]),
    dict(register="family-event-planning", phrasing="imperative",
         senders=["Papa", "Didi"],
         slots=dict(t0="TIME", e0="EVENT"),
         script="{e0} की तैयारी शुरू हो गई है। तू {t0} मेहमानों की फाइनल लिस्ट भेज दे, पक्का। और सोच रहे थे कि डेकोरेशन वाले से भी बात कर लें, वो देख लेंगे आराम से।",
         translation="The {E0} preparations have started. You send the final guest list {T0}, for sure. And we were thinking of also talking to the decorator, we will see about that at leisure.",
         summary="{sender} asks for the final guest list for the {E0} {T0}, and tentatively mentions talking to the decorator.",
         items=[("Send the final guest list for the {E0}", "t0", "confirmed"),
                ("Talk to the decorator", None, "tentative")]),
    dict(register="family-errands", phrasing="imperative",
         senders=["Papa", "Bhaiya"],
         slots=dict(t0="TIME", i0="ERRAND", p0="PLACE", b0="BILL"),
         script="सुन, {b0} मैं आज भर दूँगा, तू उसकी टेंशन मत ले। बस तू {t0} {p0} से {i0} लेते आना, मैं नहीं जा पाऊँगा।",
         translation="Listen, I will pay the {B0} today, don't worry about that. You just bring {I0} from the {P0} {T0}, I will not be able to go.",
         summary="{sender} is handling the {B0} themselves and asks only that the listener bring {I0} from the {P0} {T0}.",
         items=[("Bring {I0} from the {P0}", "t0", "confirmed")]),
    dict(register="family-chat", phrasing=None,
         senders=["Papa", "Mummy"],
         slots=dict(b0="BILL", f0="FIX"),
         script="बेटा, {b0} मैंने भर दिया है, तुझे कुछ करने की ज़रूरत नहीं। और {f0} भी ठीक करवा दिया, मिस्त्री आया था आज। बस यही बताना था। अपना ध्यान रख।",
         translation="Beta, I have paid the {B0}, you do not need to do anything. And I also got {F0} fixed, the repairman came today. That is all I wanted to say. Take care of yourself.",
         summary="{sender} reports the {B0} is already paid and {F0} has been fixed — just an update, nothing to do.",
         items=[]),
    dict(register="family-chat", phrasing=None,
         senders=["Mummy", "Cousin Aditi", "Didi"],
         slots=dict(per0="PERSON", c0="CITY"),
         script="अरे सुना तूने? {per0} के बेटे ने {c0} में नया घर बुक कर लिया। पूरे परिवार को बुलाया है गृहप्रवेश पे, सब यही बात कर रहे हैं। चल, बाद में बात करते हैं।",
         translation="Hey, did you hear? {PER0}'s son has booked a new house in {C0}. The whole family has been invited for the housewarming, everyone is talking about it. Okay, we will talk later.",
         summary="{sender} shares news that {PER0}'s son booked a house in {C0} and the family is invited to the housewarming. Pure chat, no tasks.",
         items=[]),
    dict(register="family-chat", phrasing=None,
         senders=["Dadi", "Mummy", "Bua"],
         slots=dict(per0="PERSON"),
         script="और बता, सब ठीक? खाना टाइम से खाया कर और रात को जल्दी सोया कर। यहाँ सब बढ़िया है, {per0} भी तुझे याद कर रही थीं। अपना ध्यान रख बेटा।",
         translation="And tell me, all well? Eat your meals on time and sleep early at night. Everything is fine here, {PER0} was also remembering you. Take care of yourself, beta.",
         summary="{sender} checks in with general care advice — eat on time, sleep early — and says {PER0} was remembering the listener. No tasks.",
         items=[]),
]
